;;;;;;InsertKeyChange
(if (= 1 (d-GetHorizontalPosition))
	(let ((sharps (d-GetUserInput (_ "Key Signature Change") (_ "Give a number of sharps (negative for flats):") "0"))
		(extra (d-GetUserInput (_ "Extra space") (_ "Give  any extra space before next note (Cancel for default)") "0")))
		(if (string? sharps)
			(begin

				(set! sharps (string->number sharps))	
				(if (Keysignature?)
					(begin
						(d-DeleteObject)
						(d-PushPosition)
						 (d-PushPosition)
						 (d-Copy)
						 (while (d-MoveToStaffUp)
							(if (Keysignature?) (d-DeleteObject)))
						(d-PopPosition)
						(while (d-MoveToStaffDown)
							(if (Keysignature?) (d-DeleteObject)))
						(d-PopPosition)))
				(d-InsertKey "C major")
				(d-MoveCursorLeft)
				(if (and extra (string->number extra))
					(d-DirectivePut-keysig-prefix "InsertKeyChange" 
						(string-append " \\once\\override Staff.KeySignature.space-alist.next-note = #'(semi-fixed-space . " extra ")\\once\\override Staff.KeyCancellation.space-alist.next-note = #'(semi-fixed-space . " extra ")")))
				(while (positive? sharps)
					(d-SharpenKeysig) (set! sharps (1- sharps)))
				(while (negative? sharps)
					(d-FlattenKeysig)
					 (set! sharps (1+ sharps)))
					 (d-PushPosition)
					 (d-PushPosition)
					 (d-Copy)
					 (while (d-MoveToStaffUp)
						(d-Paste))
					(d-PopPosition)
					(while (d-MoveToStaffDown)
						(d-Paste))
					(d-PopPosition))
			(d-WarningDialog (_ "Cancelled"))))
	(d-WarningDialog (_ "Cursor not at start of bar. To insert here cut and paste a key change from the start of the bar")))	
